// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // El CLI (migrate/generate) necesita la conexión DIRECTA (sin -pooler):
    // el pooler de Neon falla las migraciones por advisory lock. El runtime
    // de la app sigue usando DATABASE_URL (pooled) vía lib/prisma.ts.
    url: process.env["DIRECT_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
